## Dragon Real Estates - Price Predictor


In [1]:
import pandas as pd
import numpy as np
import re

In [2]:

housing = pd.read_csv("data.csv")

In [3]:
import os

In [4]:
os.getcwd()

'/Users/pranshukedia/Desktop/ML Project 1'

In [5]:
housing.head()

CRIM   ZN   INDUS  CHAS   NOX            RM  AGE      DIS RAD  \
0  0.00632  18.0   2.31      0       0.538  6.575  65.2  4.0900       
1  0.02731   0.0   7.07      0       0.469  6.421  78.9  4.9671   2   
2  0.02729   0.0   7.07      0       0.469  7.185  61.1  4.9671   2   
3  0.03237   0.0   2.18      0       0.458  6.998  45.8  6.0622   3   
4  0.06905   0.0   2.18      0       0.458  7.147  54.2  6.0622   3   

   TAX        PTRATIO      B   LSTAT  MEDV   
0      296.0     15.3  396.90   4.98   24.0  
1      242.0     17.8  396.90   9.14   21.6  
2      242.0     17.8  392.83   4.03   34.7  
3      222.0     18.7  394.63   2.94   33.4  
4      222.0     18.7  396.90   5.33   36.2

In [6]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   CRIM        506 non-null    float64
 1   ZN          506 non-null    float64
 2   INDUS       506 non-null    float64
 3   CHAS        506 non-null    int64  
 4   NOX         506 non-null    float64
 5   RM          506 non-null    float64
 6   AGE         506 non-null    float64
 7   DIS         506 non-null    float64
 8   RAD         506 non-null    object 
 9   TAX         506 non-null    float64
 10  PTRATIO     506 non-null    float64
 11  B           506 non-null    float64
 12  LSTAT       506 non-null    float64
 13  MEDV        506 non-null    float64
dtypes: float64(12), int64(1), object(1)
memory usage: 55.5+ KB


In [7]:
housing['CHAS '].value_counts()

0    471
1     35
Name: CHAS , dtype: int64

In [8]:
housing.describe()

CRIM         ZN        INDUS       CHAS   NOX                 RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

             AGE          DIS   TAX           PTRATIO          B        LSTAT  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043  408.237154   18.455534  356.674032   12.653063   
std     28.148861    2.105710  168.537116    2.164946   91.294864    7.141062   
min      2.900000    1.129600  187.000000   12.600000    0.320000    1.730000   
25%     45.025000    2.100175  279.000000   17.400000  375.377500    6.950000   
50%     77.500000    3.207450  330.000000   19.050000  391.440000   11.360000   
75%     94.075000    5.188425  666.000000   20.200000  396.225000   16.955000   
max    100.000000   12.126500  711.000000   22.000000  396.900000   37.970000   

            MEDV   
count  506.000000  
mean    22.532806  
std      9.197104  
min      5.000000  
25%     17.025000  
50%     21.200000  
75%     25.000000  
max     50.000000

In [9]:
%matplotlib inline
import matplotlib.pyplot as plt
#housing.hist(bins=50,figsize=(20,15))

# Train-Test Splitting

In [10]:
#def split_train_test(data, test_ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    print(shuffled)
    test_set_size=int(len(data)*test_ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

IndentationError: unexpected indent (3225565414.py, line 2)

In [ ]:
#train_set,test_set=split_train_test(housing, 0.2)

In [ ]:
#print(f"rows in train set: {len(train_set)}\nrows in test set:  {len(test_set)}")

In [11]:
from sklearn.model_selection import train_test_split
train_set,test_set=train_test_split(housing, test_size=0.2, random_state=42)
print(f"rows in train set: {len(train_set)}\nrows in test set:  {len(test_set)}")

rows in train set: 404
rows in test set:  102


In [12]:
housing.columns

Index(['CRIM', 'ZN ', 'INDUS', 'CHAS ', 'NOX       ', 'RM', 'AGE ', 'DIS',
       'RAD', 'TAX      ', 'PTRATIO', 'B ', 'LSTAT', 'MEDV '],
      dtype='object')

In [13]:
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing,housing['CHAS ']):
    strat_train_set=housing.loc[train_index]
    strat_test_set=housing.loc[test_index]

In [14]:
strat_train_set['CHAS '].value_counts()

0    376
1     28
Name: CHAS , dtype: int64

In [15]:
strat_test_set['CHAS '].value_counts()

0    95
1     7
Name: CHAS , dtype: int64

In [16]:
housing = strat_train_set.copy()

In [17]:
#corr_matrix=housing.corr()
#corr_matrix['MEDV '].sort_values(ascending=False)

In [18]:
#from pandas.plotting import scatter_matrix
#attribute=["MEDV ", "RM", "ZN ", "LSTAT"]
#scatter_matrix(housing[attribute],figsize=(12,8))

In [19]:
#housing.plot(kind="scatter", x="RM", y="MEDV ", alpha=0.8)

## seperating feature and label

In [20]:
housing=strat_train_set.drop("MEDV ",axis=1)
housing_labels=strat_train_set["MEDV "].copy()

In [21]:
housing.describe()

CRIM         ZN        INDUS       CHAS   NOX                 RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.279908   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.712983   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.210000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630250   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

             AGE          DIS   TAX           PTRATIO          B        LSTAT  
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000  
mean    69.039851    3.746210  412.341584   18.473267  353.392822   12.791609  
std     28.258248    2.099057  168.672623    2.129243   96.069235    7.235740  
min      2.900000    1.129600  187.000000   13.000000    0.320000    1.730000  
25%     44.850000    2.035975  284.000000   17.400000  374.617500    6.847500  
50%     78.200000    3.122200  337.000000   19.000000  390.955000   11.570000  
75%     94.100000    5.100400  666.000000   20.200000  395.630000   17.102500  
max    100.000000   12.126500  711.000000   22.000000  396.900000   36.980000

In [22]:
housing

CRIM   ZN   INDUS  CHAS   NOX            RM  AGE      DIS RAD  \
254  0.04819  80.0   3.64      0       0.392  6.108  32.0  9.2203   1   
348  0.01501  80.0   2.01      0       0.435  6.635  29.7  8.3440   4   
476  4.87141   0.0  18.10      0       0.614  6.484  93.6  2.3053   4   
321  0.18159   0.0   7.38      0       0.493  6.376  54.3  4.5404   5   
326  0.30347   0.0   7.38      0       0.493  6.312  28.9  5.4159   5   
..       ...   ...    ...    ...         ...    ...   ...     ...  ..   
155  3.53501   0.0  19.58      1       0.871  6.152  82.6  1.7455   5   
423  7.05042   0.0  18.10      0       0.614  6.103  85.1  2.0218   4   
98   0.08187   0.0   2.89      0       0.445  7.820  36.9  3.4952   2   
455  4.75237   0.0  18.10      0       0.713  6.525  86.5  2.4358   4   
216  0.04560   0.0  13.89      1       0.550  5.888  56.0  3.1121   5   

     TAX        PTRATIO      B   LSTAT  
254      315.0     16.4  392.89   6.57  
348      280.0     17.0  390.94   5.99  
476      666.0     20.2  396.21  18.68  
321      287.0     19.6  396.90   6.87  
326      287.0     19.6  396.90   6.15  
..         ...      ...     ...    ...  
155      403.0     14.7   88.01  15.02  
423      666.0     20.2    2.52  23.29  
98       276.0     18.0  393.53   3.57  
455      666.0     20.2   50.92  18.13  
216      276.0     16.4  392.80  13.51  

[404 rows x 13 columns]

In [23]:
housing['RAD'] = pd.to_numeric(housing['RAD'],errors = 'coerce')

In [24]:
housing.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 404 entries, 254 to 216
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   CRIM        404 non-null    float64
 1   ZN          404 non-null    float64
 2   INDUS       404 non-null    float64
 3   CHAS        404 non-null    int64  
 4   NOX         404 non-null    float64
 5   RM          404 non-null    float64
 6   AGE         404 non-null    float64
 7   DIS         404 non-null    float64
 8   RAD         403 non-null    float64
 9   TAX         404 non-null    float64
 10  PTRATIO     404 non-null    float64
 11  B           404 non-null    float64
 12  LSTAT       404 non-null    float64
dtypes: float64(12), int64(1)
memory usage: 44.2 KB


## importing a pipeline

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
my_pipeline=Pipeline([('std_scaler',StandardScaler())])

In [33]:
housing_num_tr = my_pipeline.fit_transform(housing)

In [34]:
housing_num_tr

array([[-0.43942006,  3.12628155, -1.12165014, ..., -0.97491834,
         0.41164221, -0.86091034],
       [-0.44352175,  3.12628155, -1.35893781, ..., -0.69277865,
         0.39131918, -0.94116739],
       [ 0.15682292, -0.4898311 ,  0.98336806, ...,  0.81196637,
         0.44624347,  0.81480158],
       ...,
       [-0.43525657, -0.4898311 , -1.23083158, ..., -0.22254583,
         0.41831233, -1.27603303],
       [ 0.14210728, -0.4898311 ,  0.98336806, ...,  0.81196637,
        -3.15239177,  0.73869575],
       [-0.43974024, -0.4898311 ,  0.37049623, ..., -0.97491834,
         0.41070422,  0.09940681]])

In [35]:
housing.replace([np.inf, -np.inf], np.nan, inplace=True)

In [36]:
np.nan_to_num(housing)

array([[4.81900e-02, 8.00000e+01, 3.64000e+00, ..., 1.64000e+01,
        3.92890e+02, 6.57000e+00],
       [1.50100e-02, 8.00000e+01, 2.01000e+00, ..., 1.70000e+01,
        3.90940e+02, 5.99000e+00],
       [4.87141e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96210e+02, 1.86800e+01],
       ...,
       [8.18700e-02, 0.00000e+00, 2.89000e+00, ..., 1.80000e+01,
        3.93530e+02, 3.57000e+00],
       [4.75237e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        5.09200e+01, 1.81300e+01],
       [4.56000e-02, 0.00000e+00, 1.38900e+01, ..., 1.64000e+01,
        3.92800e+02, 1.35100e+01]])

In [37]:
housing = housing.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)

## Selecting a desired model for dragon real estates

In [48]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#model=DecisionTreeRegressor()
#model=LinearRegression()
model=RandomForestRegressor()
model.fit(housing_num_tr,housing_labels)

RandomForestRegressor()

## Evaluating the model

In [49]:
from sklearn.metrics import mean_squared_error
housing_predictions=model.predict(housing_num_tr)
mse=mean_squared_error(housing_labels,housing_predictions)
rmse=np.sqrt(mse)

In [50]:
rmse

1.2493158801187276

## Using better evaluation technique - Cross Validation

In [51]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(model,housing_num_tr,housing_labels,scoring='neg_mean_squared_error',cv=10)
rmse_score=np.sqrt(-scores)

In [52]:
rmse_score

array([2.91546114, 2.70899928, 4.39564482, 2.7060339 , 3.40752099,
       2.63053869, 4.81321564, 3.30912746, 3.38857128, 3.14960412])

In [53]:
def print_scores(scores):
    print("scores:", scores)
    print("mean:",scores.mean())
    print("standard deviation:",scores.std())

In [54]:
print_scores(rmse_score)

scores: [2.91546114 2.70899928 4.39564482 2.7060339  3.40752099 2.63053869
 4.81321564 3.30912746 3.38857128 3.14960412]
mean: 3.342471730987562
standard deviation: 0.6937185802950461


## Saving the model 

In [55]:
from joblib import dump,load
dump(model, 'Dragon.joblib')

['Dragon.joblib']

## Testing the model on test data 

In [58]:
X_test=strat_test_set.drop("MEDV ",axis=1)
Y_test=strat_test_set["MEDV "].copy()
X_test_prepared=my_pipeline.transform(X_test)
final_predictions=model.predict(X_test_prepared)
final_mse=mean_squared_error(Y_test,final_predictions)
final_rmse=np.sqrt(final_mse)
print(final_predictions, list[Y_test])

[24.474 11.63  25.842 21.689 19.063 14.95  20.12  14.371 32.187 41.216
 19.475 11.603 23.469 30.187 19.567 11.283 32.376 14.466 23.711 18.645
 20.166 17.833 17.917 22.19  18.367 31.379 15.997 33.404  8.61  33.593
 24.065 21.218 22.991 10.642 21.561 11.266 43.087 24.345 23.936 41.593
 23.801 29.584 20.199 21.099 19.165 33.418 44.359 19.766 20.278 22.319
 21.175 14.879 20.755 14.819 25.062 33.476 41.859 28.719 19.31  20.61
 47.281  9.398 18.901 25.504 14.752 32.749 20.438 17.675 19.46  34.446
 26.664 22.903 21.794 22.367 34.416 11.953 15.771 20.274 20.94  21.695
 22.917 20.515 13.746 22.877 20.392 21.1   13.866 21.06  21.499 23.179
 18.784 26.978  7.14  26.234 18.551 29.81  20.071 31.848 14.073 26.86
 21.17  20.859] list[342    16.5
379    10.2
223    30.1
219    23.0
48     14.4
       ... 
88     23.6
466    19.0
52     25.0
121    20.3
218    21.5
Name: MEDV , Length: 102, dtype: float64]


In [57]:
final_rmse

2.9210865390514273

In [60]:
X_test_prepared[0]

array([-0.44228927, -0.4898311 , -1.37640684, -0.27288841, -0.34321545,
        0.36524574, -0.33092752,  1.20235683, -2.47245785,  0.05733231,
       -1.21003475,  0.38110555, -0.57309194])

## Using the model

In [61]:
from joblib import dump, load
import numpy as np
model=load('Dragon.joblib')
features = np.array([[-0.44228927, -0.4898311 , -1.37640684, -0.27288841, -0.34321545,
        0.36524574, -0.33092752,  1.20235683, -2.47245785,  0.05733231,
       -1.21003475,  0.38110555, -0.57309194]])
model.predict(features)

array([24.101])